import httpx
import asyncio
import time
from typing import Optional

# ── 인메모리 캐시 ──────────────────────────────────────────
# { cache_key: (data_dict, expires_at) }
_price_cache: dict[str, tuple[dict, float]] = {}
_PRICE_TTL = 15  # 초 (15초 캐시 — 거의 실시간)
# ticker별 개별 락: 같은 ticker 중복 요청만 직렬화, 다른 ticker는 병렬
_ticker_locks: dict[str, asyncio.Lock] = {}


def _get_lock(key: str) -> asyncio.Lock:
    if key not in _ticker_locks:
        _ticker_locks[key] = asyncio.Lock()
    return _ticker_locks[key]


def _cache_get(key: str) -> Optional[dict]:
    entry = _price_cache.get(key)
    if entry and time.monotonic() < entry[1]:
        return entry[0]
    return None


def _cache_set(key: str, data: dict):
    _price_cache[key] = (data, time.monotonic() + _PRICE_TTL)

# 홈화면 인기 종목용 (하드코딩 최소화 - ticker만 유지)
POPULAR_KR = ["005930", "000660", "035420", "035720", "005380", "373220", "068270", "247540"]
POPULAR_US = ["AAPL", "NVDA", "TSLA", "MSFT", "GOOGL", "META", "AMZN", "PLTR"]

# 미국 주식 한글 이름 매핑 (~300개)
US_NAME_KO: dict[str, str] = {
    # ── 빅테크 ──
    "AAPL": "애플",
    "MSFT": "마이크로소프트",
    "GOOGL": "알파벳(구글)",
    "GOOG": "알파벳(구글)",
    "META": "메타",
    "AMZN": "아마존",
    "NVDA": "엔비디아",
    "TSLA": "테슬라",
    "NFLX": "넷플릭스",
    "ORCL": "오라클",
    "INTC": "인텔",
    "AMD": "AMD",
    "QCOM": "퀄컴",
    "AVGO": "브로드컴",
    "TXN": "텍사스인스트루먼트",
    "MU": "마이크론",
    "AMAT": "어플라이드머티리얼즈",
    "ASML": "ASML",
    "ARM": "ARM홀딩스",
    "LRCX": "램리서치",
    "KLAC": "KLA코퍼레이션",
    "ADI": "아날로그디바이시스",
    "MRVL": "마벨테크놀로지",
    "MCHP": "마이크로칩테크놀로지",
    "MPWR": "모노리식파워시스템즈",
    "ON": "온세미컨덕터",
    "STX": "시게이트",
    "WDC": "웨스턴디지털",
    "DELL": "델테크놀로지스",
    "HPQ": "HP",
    "HPE": "휴렛팩커드엔터프라이즈",
    "IBM": "IBM",
    "CSCO": "시스코",
    "ANET": "아리스타네트웍스",
    "PALO": "팔로알토네트웍스",
    "PANW": "팔로알토네트웍스",
    "CRWD": "크라우드스트라이크",
    "ZS": "지스케일러",
    "FTNT": "포티넷",
    "OKTA": "옥타",
    "CYBR": "사이버아크",
    "S": "센티넬원",
    # ── 소프트웨어/SaaS ──
    "CRM": "세일즈포스",
    "ADBE": "어도비",
    "NOW": "서비스나우",
    "INTU": "인튜이트",
    "WDAY": "워크데이",
    "TEAM": "아틀라시안",
    "MDB": "몽고DB",
    "DDOG": "데이터독",
    "SNOW": "스노우플레이크",
    "ZM": "줌",
    "DOCU": "도큐사인",
    "TWLO": "트윌리오",
    "HUBS": "허브스팟",
    "SMAR": "스마트시트",
    "PATH": "유아이패스",
    "GTLB": "깃랩",
    "NET": "클라우드플레어",
    "CFLT": "컨플루언트",
    "BILL": "빌닷컴",
    "PAYC": "페이콤",
    "PCOR": "프로코어",
    "ASAN": "아사나",
    "BOX": "박스",
    "ESTC": "엘라스틱",
    "FROG": "JFrog",
    "APPF": "앱폴리오",
    "VCRA": "보칼리아",
    # ── 인터넷/플랫폼 ──
    "UBER": "우버",
    "LYFT": "리프트",
    "ABNB": "에어비앤비",
    "DASH": "도어대시",
    "SNAP": "스냅",
    "PINS": "핀터레스트",
    "SPOT": "스포티파이",
    "RBLX": "로블록스",
    "MTCH": "매치그룹",
    "BMBL": "범블",
    "TWTR": "트위터(X)",
    "RDDT": "레딧",
    "IAC": "IAC",
    "ANGI": "앤지",
    "YELP": "옐프",
    "TRIP": "트립어드바이저",
    "EXPE": "익스피디아",
    "BKNG": "부킹홀딩스",
    "PCLN": "프라이스라인",
    # ── 핀테크/결제 ──
    "V": "비자",
    "MA": "마스터카드",
    "AXP": "아메리칸익스프레스",
    "PYPL": "페이팔",
    "COF": "캐피탈원",
    "SQ": "블록(스퀘어)",
    "AFRM": "어펌",
    "SOFI": "소파이",
    "HOOD": "로빈후드",
    "COIN": "코인베이스",
    "MSTR": "마이크로스트래티지",
    "NU": "누홀딩스",
    "DLO": "디로컬",
    "FLYW": "플라이와이어",
    "PAYO": "페이오니어",
    "OPEN": "오픈도어",
    "OPFI": "OppFi",
    # ── 금융/은행/보험 ──
    "JPM": "JP모건",
    "BAC": "뱅크오브아메리카",
    "WFC": "웰스파고",
    "GS": "골드만삭스",
    "MS": "모건스탠리",
    "C": "씨티그룹",
    "BRK-B": "버크셔해서웨이",
    "BRK-A": "버크셔해서웨이A",
    "USB": "US뱅코프",
    "PNC": "PNC파이낸셜",
    "TFC": "트루이스트파이낸셜",
    "SCHW": "찰스슈왑",
    "BLK": "블랙록",
    "SPGI": "S&P글로벌",
    "MCO": "무디스",
    "ICE": "인터컨티넨털익스체인지",
    "CME": "CME그룹",
    "CBOE": "시카고옵션거래소",
    "FIS": "피델리티내셔널인포메이션",
    "FISV": "피서브",
    "AIG": "AIG",
    "MET": "메트라이프",
    "PRU": "프루덴셜파이낸셜",
    "AFL": "어플랙",
    "ALL": "올스테이트",
    "PGR": "프로그레시브",
    "CB": "처브",
    "HIG": "하트퍼드파이낸셜",
    # ── 소비재/유통/식품 ──
    "WMT": "월마트",
    "COST": "코스트코",
    "HD": "홈디포",
    "LOW": "로우스",
    "TGT": "타겟",
    "NKE": "나이키",
    "MCD": "맥도날드",
    "SBUX": "스타벅스",
    "KO": "코카콜라",
    "PEP": "펩시코",
    "PM": "필립모리스",
    "MO": "알트리아",
    "MDLZ": "몬델리즈",
    "GIS": "제너럴밀스",
    "K": "켈로그",
    "CPB": "캠벨수프",
    "HSY": "허쉬",
    "SJM": "JM스머커",
    "CLX": "클로록스",
    "PG": "P&G",
    "KMB": "킴벌리클라크",
    "CL": "콜게이트팜올리브",
    "CHD": "처치앤드와이트",
    "COTY": "코티",
    "EL": "에스티로더",
    "ULTA": "울타뷰티",
    "LULU": "룰루레몬",
    "PVH": "PVH",
    "RL": "랄프로렌",
    "TPR": "태피스트리",
    "VFC": "VF코퍼레이션",
    "HBI": "헤인즈브랜즈",
    "GPS": "갭",
    "URBN": "어반아웃피터스",
    "ANF": "아버크롬비앤피치",
    "AEO": "아메리칸이글",
    "AMZN": "아마존",
    "EBAY": "이베이",
    "ETSY": "엣시",
    "W": "웨이페어",
    "CHWY": "추이",
    "CVNA": "카바나",
    "KR": "크로거",
    "SFM": "스프라우츠파머스마켓",
    "CASY": "케이시스제너럴스토어",
    # ── 헬스케어/제약/바이오 ──
    "JNJ": "존슨앤존슨",
    "UNH": "유나이티드헬스",
    "PFE": "화이자",
    "ABBV": "애브비",
    "MRK": "머크",
    "LLY": "일라이릴리",
    "BMY": "브리스톨마이어스스퀴브",
    "AMGN": "암젠",
    "GILD": "길리어드사이언스",
    "BIIB": "바이오젠",
    "REGN": "리제네론",
    "VRTX": "버텍스파마슈티컬스",
    "MRNA": "모더나",
    "BNTX": "바이오엔테크",
    "NVAX": "노바백스",
    "ILMN": "일루미나",
    "IQV": "IQVIA",
    "A": "에질런트테크놀로지스",
    "TMO": "써모피셔사이언티픽",
    "DHR": "다나허",
    "SYK": "스트라이커",
    "BSX": "보스턴사이언티픽",
    "MDT": "메드트로닉",
    "ABT": "애보트래버러토리스",
    "EW": "에드워즈라이프사이언시스",
    "ZBH": "짐머바이오멧",
    "BAX": "박스터",
    "BDX": "벡턴디킨슨",
    "CVS": "CVS헬스",
    "CI": "시그나",
    "HUM": "휴마나",
    "CNC": "센틴",
    "MOH": "몰리나헬스케어",
    "TDOC": "텔라닥",
    "ACCD": "액코이드헬스",
    # ── 에너지 ──
    "XOM": "엑슨모빌",
    "CVX": "셰브런",
    "COP": "코노코필립스",
    "EOG": "EOG리소시스",
    "SLB": "슐럼버거",
    "HAL": "핼리버튼",
    "BKR": "베이커휴즈",
    "OXY": "옥시덴탈페트롤리엄",
    "DVN": "데본에너지",
    "FANG": "다이아몬드백에너지",
    "MPC": "마라톤페트롤리엄",
    "PSX": "필립스66",
    "VLO": "발레로에너지",
    "KMI": "킨더모건",
    "WMB": "윌리엄스컴퍼니스",
    "ET": "에너지트랜스퍼",
    "LNG": "셰니어에너지",
    # ── 통신/미디어 ──
    "DIS": "디즈니",
    "CMCSA": "컴캐스트",
    "T": "AT&T",
    "VZ": "버라이즌",
    "TMUS": "T모바일",
    "CHTR": "차터커뮤니케이션스",
    "PARA": "파라마운트글로벌",
    "WBD": "워너브라더스디스커버리",
    "FOXA": "폭스",
    "NWSA": "뉴스코프",
    "NYT": "뉴욕타임스",
    "LYV": "라이브네이션",
    "SIRI": "시리우스XM",
    # ── 산업재/항공/방산 ──
    "BA": "보잉",
    "LMT": "록히드마틴",
    "RTX": "RTX(레이시온)",
    "NOC": "노스롭그루먼",
    "GD": "제너럴다이나믹스",
    "HII": "헌팅턴잉걸스",
    "TDG": "트랜스다임",
    "GE": "GE에어로스페이스",
    "HON": "하니웰",
    "MMM": "3M",
    "EMR": "에머슨일렉트릭",
    "ETN": "이튼",
    "PH": "파커해니핀",
    "ROK": "로크웰오토메이션",
    "IR": "잉거솔랜드",
    "CMI": "커민스",
    "CAT": "캐터필러",
    "DE": "존디어",
    "AGCO": "AGCO",
    "UPS": "UPS",
    "FDX": "페덱스",
    "DAL": "델타항공",
    "UAL": "유나이티드항공",
    "AAL": "아메리칸항공",
    "LUV": "사우스웨스트항공",
    "ALK": "알래스카항공",
    "JBLU": "젯블루",
    "CCL": "카니발",
    "RCL": "로열캐리비언",
    "NCLH": "노르웨지언크루즈",
    "MAR": "매리어트",
    "HLT": "힐튼",
    "H": "하얏트",
    "WH": "윈덤호텔",
    "HGV": "힐튼그랜드베케이션스",
    # ── 부동산(REIT) ──
    "AMT": "아메리칸타워",
    "PLD": "프로로지스",
    "CCI": "크라운캐슬",
    "EQIX": "에퀴닉스",
    "SPG": "사이먼프로퍼티그룹",
    "O": "리얼티인컴",
    "VICI": "VICI프로퍼티스",
    "WELL": "웰타워",
    "DLR": "디지털리얼티",
    "PSA": "퍼블릭스토리지",
    "EXR": "엑스트라스페이스스토리지",
    "AVB": "에벌론베이커뮤니티스",
    "EQR": "에퀴티레지덴셜",
    "ARE": "알렉산드리아리얼에스테이트",
    "VTR": "벤타스",
    "PEAK": "헬스피크프로퍼티스",
    # ── 전기차/미래모빌리티 ──
    "TSLA": "테슬라",
    "RIVN": "리비안",
    "LCID": "루시드모터스",
    "NIO": "니오",
    "XPEV": "샤오펑",
    "LI": "리오토모",
    "FFIE": "패러데이퓨처",
    "GOEV": "카누",
    "FSR": "피스커",
    "WKHS": "워크호스",
    "RIDE": "로즈타운모터스",
    "SOLO": "일렉트라메카니카",
    "PTRA": "프로테라",
    # ── 중국 ADR ──
    "BABA": "알리바바",
    "JD": "징둥닷컴",
    "BIDU": "바이두",
    "PDD": "핀둬둬(테무)",
    "TCEHY": "텐센트",
    "NTES": "넷이즈",
    "BEKE": "KE홀딩스",
    "TAL": "TAL에듀케이션",
    "EDU": "뉴오리엔탈",
    "IQ": "아이치이",
    "BILI": "빌리빌리",
    "VIPS": "유핀",
    "WB": "웨이보",
    "MOMO": "하이피",
    "ZH": "지후",
    "TIGR": "업스탁스",
    "FUTU": "푸투홀딩스",
    # ── 우주/방산 신흥 ──
    "SPCE": "버진갤럭틱",
    "RKT": "로켓컴퍼니스",
    "ASTS": "AST스페이스모바일",
    "LUNR": "인튜이티브머신스",
    "RKLB": "로켓랩",
    "MNTS": "모멘투스",
    "ASTR": "아스트라",
    # ── AI/반도체 신흥 ──
    "AI": "C3.ai",
    "BBAI": "빅베어AI",
    "SOUN": "사운드하운드AI",
    "VNET": "21비아넷",
    "SMCI": "슈퍼마이크로컴퓨터",
    "IONQ": "아이온큐",
    "RGTI": "리게티컴퓨팅",
    "QUBT": "퀀텀컴퓨팅",
    "QBTS": "D-Wave퀀텀",
    "ARQQ": "아쿼안텀",
    # ── ETF ──
    "SPY": "S&P500 ETF",
    "QQQ": "나스닥100 ETF",
    "DIA": "다우존스 ETF",
    "IWM": "러셀2000 ETF",
    "VTI": "미국 전체주식 ETF",
    "VOO": "뱅가드 S&P500 ETF",
    "VGT": "뱅가드 IT섹터 ETF",
    "XLK": "테크섹터 ETF",
    "XLF": "금융섹터 ETF",
    "XLE": "에너지섹터 ETF",
    "XLV": "헬스케어섹터 ETF",
    "XLY": "임의소비재섹터 ETF",
    "XLP": "필수소비재섹터 ETF",
    "XLI": "산업재섹터 ETF",
    "XLB": "소재섹터 ETF",
    "XLRE": "부동산섹터 ETF",
    "XLC": "통신섹터 ETF",
    "XLU": "유틸리티섹터 ETF",
    "ARKK": "ARK 이노베이션 ETF",
    "ARKQ": "ARK 자율기술&로봇 ETF",
    "ARKW": "ARK 차세대인터넷 ETF",
    "ARKG": "ARK 유전체혁명 ETF",
    "SOXX": "반도체 ETF",
    "SOXL": "반도체 3배 레버리지 ETF",
    "SOXS": "반도체 3배 인버스 ETF",
    "TQQQ": "나스닥100 3배 레버리지 ETF",
    "SQQQ": "나스닥100 3배 인버스 ETF",
    "UPRO": "S&P500 3배 레버리지 ETF",
    "SPXS": "S&P500 3배 인버스 ETF",
    "TLT": "미국 장기국채 ETF",
    "SHY": "미국 단기국채 ETF",
    "HYG": "하이일드채권 ETF",
    "LQD": "투자등급회사채 ETF",
    "GLD": "금 ETF",
    "SLV": "은 ETF",
    "USO": "원유 ETF",
    "UNG": "천연가스 ETF",
    "IBIT": "블랙록 비트코인 ETF",
    "FBTC": "피델리티 비트코인 ETF",
    "BITO": "비트코인 선물 ETF",
    "EEM": "신흥시장 ETF",
    "EFA": "선진국(미국제외) ETF",
    "EWJ": "일본 ETF",
    "MCHI": "중국 ETF",
    "EWY": "한국 ETF",
    "KWEB": "중국 인터넷 ETF",
    "FXI": "중국 대형주 ETF",
    "CQQQ": "중국 테크 ETF",
    # ── AI/데이터/클라우드 (추가) ──
    "PLTR": "팔란티어",
    "SNOW": "스노우플레이크",
    "DDOG": "데이터독",
    "ESTC": "엘라스틱",
    "SUMO": "수모로직",
    "DT": "다이나트레이스",
    "NEWR": "뉴렐릭",
    "SPLK": "스플렁크",
    "PTC": "PTC",
    "ANSS": "앤시스",
    "CDNS": "케이던스디자인",
    "SNPS": "시놉시스",
    "MANH": "맨하탄어소시에이츠",
    "VEEV": "비바시스템즈",
    "CDAY": "세리디언HCM",
    "RCM": "R1RCM",
    "NUAN": "뉴앙스커뮤니케이션스",
    "APPN": "앱피안",
    "PEGA": "페가시스템즈",
    "PRFT": "퍼펙트",
    "GWRE": "가이드와이어소프트웨어",
    "BL": "블랙라인",
    "AZPN": "아스펜테크놀로지",
    "ALTR": "알타이르엔지니어링",
    "CTRE": "케어트러스트REIT",
    "TOST": "토스트",
    "FIVN": "파이브나인",
    "NICE": "NICE시스템즈",
    "ZI": "줌인포",
    "BRZE": "브레이즈",
    "ALRM": "알람닷컴",
    "ARLO": "알로테크놀로지스",
    "JAMF": "JAMF홀딩",
    "CNXC": "콘센트릭스",
    "TTEC": "TTEC홀딩스",
    "CWAN": "클리어워터애널리틱스",
    "INTA": "인타",
    "OBNK": "오리진뱅코프",
    "FORR": "포레스터리서치",
    "PRGS": "프로그레스소프트웨어",
    "ALKT": "알렉타",
    "WEAV": "위브",
    "TASK": "태스크어스",
    "RELY": "레밸리",
    "LPSN": "라이브퍼슨",
    "TALK": "딕시컴",
    "AGYS": "아질리시스",
    "AVLR": "아발라라",
    "CPRT": "코파트",
    "WLTW": "윌리스타워스왓슨",
    "BR": "브로드리지파이낸셜",
    "SS": "스털링인프라",
    "RBA": "RB글로벌",
    "CSGP": "코스타그룹",
    "MTTR": "매터포트",
    "OPEN": "오픈도어",
    "OPAD": "오퍼패드",
    "RDFN": "레드핀",
    "HOUS": "비바홈",
    # ── 반도체 추가 ──
    "WOLF": "울프스피드",
    "SWKS": "스카이웍스솔루션즈",
    "QRVO": "코르보",
    "CRUS": "서러스로직",
    "SLAB": "실리콘랩스",
    "SITM": "사이타임",
    "DIOD": "다이오드",
    "RMBS": "램버스",
    "ACLS": "액셀리스테크놀로지스",
    "FORM": "폼팩터",
    "COHU": "코후",
    "ICHR": "이코르홀딩스",
    "UCTT": "울트라클린홀딩스",
    "AMKR": "암코테크놀로지",
    "ONTO": "온토이노베이션",
    "CAMT": "카메텍",
    "NVMI": "노바미저링",
    "AAOI": "아플라이드옵토일렉트로닉스",
    "AMBA": "암바렐라",
    "VIAV": "비아비솔루션즈",
    "IPHI": "인피",
    "LITE": "라이버트",
    "IIVI": "II-VI",
    "OLED": "유니버설디스플레이",
    "KLIC": "쿨리케앤소파",
    "ENTG": "엔테그리스",
    "CCMP": "CMC머티리얼즈",
    "MKSI": "MKS인스트루먼츠",
    "ONTO": "온토이노베이션",
    "PI": "임페인지",
    "POWI": "파워인테그레이션스",
    "MPWR": "모노리식파워시스템즈",
    "VSH": "비샤이인터텍",
    "ALGM": "알레그로마이크로시스템즈",
    "EGAN": "이갠",
    "AXTI": "AXT",
    "IART": "인테그라라이프사이언시스",
    "NVEC": "NVE코퍼레이션",
    "SYNA": "시냅틱스",
    "NXPI": "NXP세미컨덕터스",
    "STM": "ST마이크로일렉트로닉스",
    "IFX": "인피니온테크놀로지스",
    "RENESAS": "르네사스일렉트로닉스",
    # ── 바이오테크/제약 추가 ──
    "ALNY": "알나일람파마슈티컬스",
    "BMRN": "바이오마린파마슈티컬",
    "INCY": "인사이트",
    "EXAS": "엑세트",
    "RARE": "울트라제닉스파마슈티컬",
    "DNLI": "드나리테라퓨틱스",
    "ARWR": "애로우헤드파마슈티컬스",
    "MRTX": "마라베릭테라퓨틱스",
    "KRTX": "카루나테라퓨틱스",
    "RCUS": "아르커스바이오사이언시스",
    "MGNX": "맥로제넥스",
    "LEGN": "레전드바이오텍",
    "FOLD": "아미커스테라퓨틱스",
    "SRPT": "사렙타테라퓨틱스",
    "NBIX": "뉴로크라인바이오사이언시스",
    "IONS": "아이오니스파마슈티컬스",
    "IMVT": "이뮤노반트",
    "ARCT": "아르코터스테라퓨틱스",
    "AGIO": "아게이오스파마슈티컬스",
    "BLUE": "블루버드바이오",
    "EDIT": "에디타스메디신",
    "NTLA": "인텔리아테라퓨틱스",
    "CRSP": "크리스퍼테라퓨틱스",
    "BEAM": "빔테라퓨틱스",
    "PACB": "퍼시픽바이오사이언시스",
    "NKTR": "넥타테라퓨틱스",
    "PRTA": "프로테나",
    "HALO": "할로자임테라퓨틱스",
    "IDYA": "아이디야바이오사이언시스",
    "FATE": "페이트테라퓨틱스",
    "BCYC": "바이시클테라퓨틱스",
    "IMMU": "이뮤노메딕스",
    "ACAD": "ACADIA파마슈티컬스",
    "SAGE": "세이지테라퓨틱스",
    "AERI": "에어리파마슈티컬스",
    "ITCI": "인트라셀룰러테라피",
    "INVA": "이노비아파마슈티컬스",
    "ARDX": "아라덱스테라퓨틱스",
    "FLXN": "플렉시온테라퓨틱스",
    "ANAB": "아나바이오파마슈티컬스",
    "PTGX": "프로테아제파마",
    "RGEN": "레프로젠",
    "OYST": "오이스터포인트파마",
    "REPL": "레플리겐",
    "BPMC": "블루프린트메디신",
    "TGTX": "TG테라퓨틱스",
    "KPTI": "카리오파마테라퓨틱스",
    "EPZM": "에피자임",
    "VRNA": "베로나파마",
    "ACVX": "아쿠비타스",
    "XNCR": "제넥서스파마슈티컬스",
    "TTOO": "T2바이오시스템즈",
    "RXDX": "이그나이타",
    "TSVT": "2세브레테라퓨틱스",
    "MRUS": "메러스",
    "KYMR": "카이메라테라퓨틱스",
    "AKBA": "아케비아테라퓨틱스",
    "IMCR": "이뮤니코어",
    "FDMT": "파운데이션메디신",
    "ZYME": "자이모젠틱스",
    "LQDA": "리킬라테라퓨틱스",
    "CELC": "셀사이언스",
    "DAWN": "도로시아바이오",
    "RVMD": "레볼루션메디신즈",
    "AUPH": "아우리니아파마슈티컬스",
    "VCEL": "벨셀테라퓨틱스",
    "DVAX": "다이나백스테크놀로지스",
    "NUVL": "누발렌트",
    "PRME": "프라임메디슨",
    "RNA": "아바나스테라퓨틱스",
    "GOSS": "고세리파마슈티컨",
    # ── 핀테크/금융 추가 ──
    "UPST": "업스타트홀딩스",
    "LC": "렌딩클럽",
    "ONDK": "온덱캐피탈",
    "GCBC": "그린에이커스",
    "LMND": "레모네이드",
    "ROOT": "루트인슈어런스",
    "HIPO": "히포홀딩스",
    "MGNI": "매그나이트",
    "PERI": "페리온네트워크",
    "SMAR": "스마트시트",
    "RELY": "레밸리파이낸셜",
    "KNSL": "카인슬리",
    "RYAN": "라이언스페셜티그룹",
    "SHAK": "셰이크쉑",
    "DFS": "디스커버파이낸셜",
    "SYF": "싱크로니파이낸셜",
    "ALLY": "알리파이낸셜",
    "NMIH": "NMI홀딩스",
    "ESNT": "에센트그룹",
    "PFSI": "PennyMac파이낸셜",
    "UWMC": "UWM홀딩스",
    "GHLD": "길드모기지",
    "HMPT": "홈포인트캐피탈",
    "TREE": "렌딩트리",
    "QFIN": "360다이지텍",
    "FINV": "핀볼트그룹",
    "CURO": "큐로그룹",
    "WRLD": "월드어셉턴스",
    "MFIN": "메디콤홀딩스",
    "EZCORP": "EZCORP",
    "FG": "F&G애뉴이티",
    "ORI": "올드리퍼블릭인터내셔널",
    "THG": "핸오버인슈어런스",
    "RLI": "RLI코프",
    "EMC": "EMC인슈어런스",
    "SIGI": "셀렉티브인슈어런스",
    "ACGL": "아치캐피탈그룹",
    "ARGO": "아르고그룹",
    "KMPR": "켐퍼",
    "ERIE": "이리인뎀니티",
    "CINF": "신시내티파이낸셜",
    "STFC": "스테이트오토",
    "UVE": "유니버설보험홀딩스",
    "HCI": "HCI그룹",
    "FNHC": "페더레이티드내셔널",
    # ── 소비재/브랜드 추가 ──
    "ONON": "온홀딩",
    "BIRD": "올버즈",
    "SKECHERS": "스케쳐스",
    "SKX": "스케쳐스",
    "CROX": "크록스",
    "DECK": "데커스아웃도어",
    "WWW": "볼버린월드와이드",
    "BOOT": "부트반",
    "SHOO": "스티브마든",
    "SCVL": "슈카니발",
    "HIMS": "힘스앤드허스홀딩스",
    "CURV": "토리드홀딩스",
    "LOVE": "러브삭",
    "WSM": "윌리엄스소노마",
    "RH": "RH(레스토레이션하드웨어)",
    "ARHAUS": "아하우스",
    "ARHS": "아하우스",
    "LESL": "레슬리스풀스",
    "XPOF": "엑스포넨셜피트니스",
    "PLNT": "플래닛피트니스",
    "PTON": "펠로톤",
    "NCLH": "노르웨지언크루즈라인",
    "HAS": "해즈브로",
    "MAT": "마텔",
    "JAKK": "JAKKS퍼시픽",
    "LEGO": "레고",
    "FNKO": "펑코",
    "GIL": "길단액티브웨어",
    "COLM": "컬럼비아스포츠웨어",
    "RKWW": "록키마운틴하이",
    "CAL": "칼란드패션그룹",
    "JOAN": "조앤스토어스",
    "TUYA": "투야스마트",
    "YSX": "요시",
    "MNSO": "MINISO",
    "BTBT": "비트디지털",
    "YMM": "풀트럭얼라이언스",
    "DIDI": "디디글로벌",
    "KANZHUN": "보스직빙",
    "BZ": "KANZHUN(보스직빙)",
    "RLX": "RLX테크놀로지",
    "DQ": "다코그린에너지",
    "JKS": "징코솔라",
    "CSIQ": "캐나디안솔라",
    "MAXN": "맥시온솔라",
    "ARRY": "어레이테크놀로지스",
    "ENPH": "엔페이즈에너지",
    "SEDG": "솔라엣지테크놀로지스",
    "FSLR": "퍼스트솔라",
    "RUN": "선런",
    "SPWR": "선파워",
    "NOVA": "사비야홀딩스",
    "SHLS": "셸스테크놀로지스",
    "STEM": "스템",
    "BE": "블룸에너지",
    "PLUG": "플러그파워",
    "FCEL": "퓨얼셀에너지",
    "HYLN": "하일리온",
    "HYZN": "헤이즌에너지",
    "REX": "REX에너지",
    "CLNE": "클린에너지퓨얼스",
    "AMRC": "암필라이트에너지서비스",
    "GPRE": "그린플레인스",
    "REX": "렉스에너지",
    "NRGU": "마이크로섹터US빅오일3x",
    # ── 음식/외식/식품 ──
    "CMG": "치폴레멕시칸그릴",
    "YUM": "얌브랜즈",
    "QSR": "레스토랑브랜즈인터내셔널",
    "DPZ": "도미노피자",
    "DRI": "다든레스토랑",
    "TXRH": "텍사스로드하우스",
    "EAT": "빈가이",
    "JACK": "잭인더박스",
    "SHAK": "셰이크쉑",
    "WEN": "웬디스",
    "BJ": "BJs레스토랑",
    "CAKE": "치즈케이크팩토리",
    "RRGB": "레드로빈",
    "BLMN": "블루밍브랜즈",
    "FRSH": "카보베르데",
    "NATH": "내이선스페이머스",
    "KRUS": "쿠라스시",
    "BJRI": "BJ스레스토랑",
    "HABT": "해빗레스토랑",
    "FRGI": "파이어하우스레스토랑그룹",
    "DENN": "데니스",
    "IHOP": "아이홉",
    "PLAY": "데이브앤버스터스",
    "ARCO": "아르코스도라도스홀딩스",
    "RAVE": "레이브레스토랑그룹",
    "WING": "윙스탑",
    "DINE": "다인브랜즈글로벌",
    "RAX": "루비튜즈데이",
    "SG": "스위트그린",
    "PTLO": "포르타벨라",
    "KRUS": "쿠라스시바",
    "NURO": "누로",
    "TAC": "트리플에이",
    "VLNS": "비올라",
    "SPB": "스펙트럼브랜즈",
    "KHC": "크래프트하인즈",
    "MKC": "맥코믹",
    "TR": "테ootsie롤",
    "JJSF": "JJ스나크푸드",
    "CALM": "칼-메인푸드",
    "SAFM": "샌더슨팜스",
    "LNDC": "랜드씨아그리",
    "IPAR": "인터파르펌",
    "THS": "트리하우스푸드",
    "B&G": "B&G푸드",
    "BGS": "B&G푸드",
    # ── 헬스케어 추가 ──
    "DGX": "퀘스트다이아그노스틱스",
    "LH": "래버러토리오브아메리카",
    "HCAT": "헬스카탈리스트",
    "PHR": "파이어플라이헬스",
    "ONEM": "원메디컬",
    "ACMR": "ACM리서치",
    "OM": "오우트셋메디컬",
    "BLFS": "바이오라이프솔루션스",
    "MMSI": "메리디언바이오사이언시스",
    "MLAB": "메사랩스",
    "NTRA": "나테라",
    "CGEN": "컴퓨젠",
    "XNCR": "제넥서스",
    "TBPH": "테오라빅파마슈티컬스",
    "HRTX": "헤론테라퓨틱스",
    "HRMY": "하모니바이오사이언시스",
    "AGEN": "아제너스",
    "ADMA": "ADMA바이올로직스",
    "MNKD": "맨카인드코퍼레이션",
    "ELAN": "엘란코애니멀헬스",
    "PRAH": "PRA헬스사이언시스",
    "IRHC": "아이언힐스헬스케어",
    "PAHC": "PAH케어",
    "PRAXIS": "프락시스바이오텍",
    "PRTK": "파라텍파마슈티컬스",
    "VNDA": "벤다파마슈티컬스",
    "SUPN": "수페너스파마슈티컬스",
    "COLL": "콜라르미드",
    "CNMD": "CONMED",
    "ATRC": "아트리큐어",
    "NUVA": "NuVasive",
    "GKOS": "글라우코스",
    "LNTH": "랜테우스홀딩스",
    "NVCR": "노보큐어",
    "NARI": "이나리메디컬",
    "INIO": "이노바이오파마슈티컬스",
    "INVA": "이노바",
    "NEOS": "네오스테라퓨틱스",
    "ALXO": "알렉소온코",
    "PRTA": "프로테나",
    "VKTX": "바이킹테라퓨틱스",
    "KALA": "칼라바이오파마",
    "EVLO": "에볼렌트바이오사이언스",
    "TCRR": "TCR2테라퓨틱스",
    "IMVT": "이뮤노반트",
    "OGN": "오가논앤컴퍼니",
    "PRGO": "페리고",
    "ENDP": "엔도인터내셔널",
    "BHC": "보슈헬스",
    "HLN": "할레온",
    "KVUE": "켄뷰",
    # ── 전기/유틸리티/청정에너지 ──
    "NEE": "넥스트에라에너지",
    "DUK": "듀크에너지",
    "SO": "서던컴퍼니",
    "D": "도미니언에너지",
    "AEP": "아메리칸일렉트릭파워",
    "EXC": "엑셀론",
    "SRE": "셈프라에너지",
    "PCG": "PG&E",
    "ED": "컨솔리데이티드에디슨",
    "ES": "에버소스에너지",
    "FE": "퍼스트에너지",
    "PPL": "PPL코퍼레이션",
    "CMS": "CMS에너지",
    "NI": "니소스",
    "AES": "AES코퍼레이션",
    "WEC": "WEC에너지그룹",
    "ETR": "엔터지",
    "EVRG": "에버게이",
    "LNT": "알라인트에너지",
    "OGE": "OGE에너지",
    "PNW": "피나클웨스트캐피탈",
    "ATO": "아토스",
    "NWE": "노스웨스턴에너지",
    "AVA": "아비스타",
    "MGEE": "MGE에너지",
    "ELP": "컴파니아파라나엔세",
    "ENIA": "에넬아메리카스",
    "ENGI": "에넬칠레",
    "CPL": "컴파니아에너지아",
    # ── 산업재/제조 추가 ──
    "RSG": "리퍼블릭서비시스",
    "WM": "웨이스트매니지먼트",
    "CLH": "클린하버스",
    "SRCL": "스테리사이클",
    "GFL": "GFL환경",
    "HCCI": "헤리티지크리스탈클린",
    "CECO": "CECO환경",
    "NFBK": "노퍽뱅코프",
    "GGG": "그라코",
    "ITW": "일리노이툴웍스",
    "AME": "AMETEK",
    "FTV": "포티브",
    "NVT": "엔벤트일렉트릭",
    "GNRC": "제너락홀딩스",
    "HUBB": "허벨",
    "REXNORD": "렉스노드",
    "RXN": "렉스노드",
    "XYL": "자이렘",
    "WTS": "왓츠워터",
    "MWA": "뮬러워터프로덕츠",
    "PRMW": "프리미엄워터스",
    "BYND": "비욘드미트",
    "APPH": "앱하비스트",
    "AQB": "아쿠아바운티테크놀로지스",
    "AGFS": "에그리포스",
    "LAND": "글래드스톤랜드",
    "FPI": "팜랜드파트너스",
    "VITL": "바이탈팜스",
    "HAIN": "헤인셀레스티얼",
    "SMPL": "심플밀스",
    "TWNK": "호스티스브랜즈",
    "CAKE": "치즈케이크팩토리",
    "NDLS": "누들앤컴퍼니",
    "MDRN": "모던레스토랑그룹",
    "PPC": "필그림스프라이드",
    "TSN": "타이슨푸드",
    "HRL": "호멜푸드",
    "LANC": "랭커스터콜로니",
    "POST": "포스트홀딩스",
    "RAH": "랄스턴퓨리나",
    # ── 부동산/건설 ──
    "LEN": "레나",
    "DHI": "DR호튼",
    "PHM": "풀트그룹",
    "TOL": "톨브라더스",
    "MDC": "MDC홀딩스",
    "TMHC": "테일러모리슨홈",
    "MTH": "메리티지홈즈",
    "SKY": "스카일라인챔피언",
    "CVCO": "캐벌리어홈스",
    "GRBK": "그린브릭파트너스",
    "LGIH": "LGI홈즈",
    "AZEK": "AZEK컴퍼니",
    "TREX": "트렉스컴퍼니",
    "FBHS": "포춘브랜즈홈앤시큐리티",
    "JELD": "JELD-WEN홀딩",
    "MHK": "모호크인더스트리스",
    "TILE": "인터페이스",
    "AIN": "알버니인터내셔널",
    "DOOR": "마스터도어",
    "SSD": "심슨매뉴팩처링",
    "BLDR": "빌더스퍼스트소스",
    "UFP": "UFP테크놀로지스",
    "IBP": "설치드빌딩프로덕츠",
    "COCS": "컴퍼스",
    "COMP": "컴퍼스",
    "EXP": "이글머티리얼스",
    "USG": "USG",
    "MLM": "마틴마리에타머티리얼스",
    "VMC": "불칸머티리얼스",
    "SUM": "서미트머티리얼스",
    "CRH": "CRH",
    "USCR": "US콘크리트",
    "GMS": "GMS",
    "STLD": "스틸다이나믹스",
    "NUE": "뉴코",
    "CLF": "클리블랜드클리프스",
    "X": "US스틸",
    "CMC": "커머셜메탈스",
    "RS": "렐라이언스스틸앤알루미늄",
    "GGB": "게르다우",
    "SID": "CSN(브라질철강)",
    "VALE": "발레(브라질광산)",
    "FCX": "프리포트맥모란",
    "AA": "알코아",
    "CENX": "센추리알루미늄",
    "KALU": "카이저알루미늄",
    "ARNC": "아르코닉",
    "HBM": "허드베이미네랄스",
    "TECK": "테크리소시스",
    "BHP": "BHP그룹",
    "RIO": "리오틴토",
    "SCCO": "서던코퍼",
    "MP": "MP머티리얼스",
    "NOVG": "노보리소시스",
    # ── 이커머스/물류 ──
    "SE": "씨그룹(쇼피)",
    "GRAB": "그랩홀딩스",
    "GOTO": "GoTo그룹",
    "MELI": "메르카도리브레",
    "PAGS": "페이그먼트",
    "VTEX": "VTEX",
    "LZKB": "레즈칸",
    "GLOB": "글로반트",
    "GPN": "글로벌페이먼츠",
    "WEX": "WEX",
    "EVERI": "에버리홀딩스",
    "EVVR": "에버리홀딩스",
    "PAX": "팍스글로벌테크놀로지",
    "STNE": "스톤컴파이",
    "ECOM": "채널어드바이저",
    "BIGC": "빅커머스",
    "SHOP": "쇼피파이",
    "PRTS": "카파츠닷컴",
    "SPS": "레크리에이셔널닷컴",
    "KAR": "OPENLANE",
    "IAA": "IAA",
    "CPNG": "쿠팡",
    "LAZR": "루미나테크놀로지스",
    "LIDR": "에이이이레이더",
    "INVZ": "이노비즈테크놀로지스",
    "OUST": "오스터",
    "AEVA": "에바테크놀로지스",
    "MVIS": "마이크로비전",
    "PCVX": "베러스파마슈티컬스",
    # ── 자율주행/로봇 ──
    "MBLY": "모빌아이글로벌",
    "APTV": "앱티브",
    "TEN": "테넥오토모티브",
    "LEA": "리어",
    "MGA": "마그나인터내셔널",
    "ADNT": "아디언트",
    "GNTX": "젠텍스",
    "VLTO": "베랄토",
    "BRKR": "브루커",
    "AZTA": "아즈타솔라",
    "FLR": "플루어",
    "PWR": "퀀타서비시스",
    "CACI": "CACI인터내셔널",
    "LDOS": "레이도스홀딩스",
    "SAIC": "SAIC",
    "BAH": "부즈앨런해밀턴",
    "CSRA": "CSRA",
    "DXC": "DXC테크놀로지",
    "EXLS": "엑스라이트애널리틱스",
    "EPAM": "EPAM시스템즈",
    "GLOB": "글로반트",
    "ACN": "액센추어",
    "CTSH": "코그니전트테크놀로지솔루션즈",
    "WIT": "위프로",
    "INFY": "인포시스",
    "HCL": "HCL테크놀로지스",
    "TCS": "TCS",
    "KFIN": "카레라금융",
    # ── 인도/이머징마켓 ADR ──
    "IBN": "ICICI은행",
    "HDB": "HDFC은행",
    "SBIN": "SBI은행",
    "WIT": "위프로",
    "INFY": "인포시스",
    "AAON": "아이온",
    "RDY": "닥터레디스래버러토리스",
    "CIPLA": "시플라",
    "LT": "라센앤투브로",
    "BHARTI": "바르티에어텔",
    "RELIANCE": "릴라이언스인더스트리스",
    "TATAMOTORS": "타타모터스",
    "TTM": "타타모터스",
    "HMC": "혼다모터",
    "TM": "도요타",
    "SONY": "소니그룹",
    "SNE": "소니그룹",
    "NTDOY": "닌텐도",
    "MUFG": "미쓰비시UFJ",
    "SMFG": "스미토모미쓰이",
    "MFG": "미즈호파이낸셜",
    "NMR": "노무라홀딩스",
    "SHI": "시세이도",
    "KB": "KB금융",
    "SHG": "신한지주",
    "WF": "우리금융",
    "PKX": "POSCO홀딩스",
    "KEP": "한국전력",
    "SKM": "SK텔레콤",
    "CTRP": "씨트립(트립닷컴)",
    "TCOM": "트립닷컴그룹",
    "HTHT": "화주(H월드)",
    "GHI": "그린힐",
    "ATHM": "오토홈",
    "LPSN": "라이브퍼슨",
    "LABU": "바이오테크 3배 레버리지 ETF",
    "LABD": "바이오테크 3배 인버스 ETF",
    "BOIL": "천연가스 2배 레버리지 ETF",
    "KOLD": "천연가스 2배 인버스 ETF",
    "UCO": "원유 2배 레버리지 ETF",
    "SCO": "원유 2배 인버스 ETF",
    "GUSH": "에너지 2배 레버리지 ETF",
    "DRIP": "에너지 2배 인버스 ETF",
    "NUGT": "금광주 2배 레버리지 ETF",
    "DUST": "금광주 2배 인버스 ETF",
    "JNUG": "금광주 3배 레버리지 ETF",
    "JDST": "금광주 3배 인버스 ETF",
    "SILJ": "소형 은광주 ETF",
    "GDXJ": "소형 금광주 ETF",
    "GDX": "금광주 ETF",
    "GDXJ": "소형금광주 ETF",
    "IAU": "iShares 금 ETF",
    "SGOL": "골드 ETF",
    "PHYS": "물리적금 ETF",
    "PSLV": "물리적은 ETF",
    "PPLT": "플래티넘 ETF",
    "PALL": "팔라듐 ETF",
    "DBA": "농산물 ETF",
    "DBC": "원자재 ETF",
    "PDBC": "원자재 ETF(비과세)",
    "DBB": "베이스메탈 ETF",
    "DBP": "귀금속 ETF",
    "REMX": "희토류 ETF",
    "PICK": "금속&광업 ETF",
    "COPX": "구리광업 ETF",
    "SIL": "은광주 ETF",
    "LIT": "리튬&배터리 ETF",
    "BATT": "배터리기술 ETF",
    "DRIV": "전기차&드라이빙기술 ETF",
    "IDRV": "iShares 전기차 ETF",
    "KARS": "KraneShares 전기차 ETF",
    "HAIL": "SPDR S&P카이어스 ETF",
    "MOTO": "스마트모빌리티 ETF",
    "BLOK": "블록체인 ETF",
    "DAPP": "디지털자산&블록체인 ETF",
    "BITQ": "크립토인더스트리&디지털경제 ETF",
    "WGMI": "비트코인마이닝 ETF",
    "SATO": "사토시액션펀드 ETF",
    "BITI": "비트코인인버스 ETF",
    "BTAL": "대형주-소형주 인버스 ETF",
    "TAIL": "테일리스크 ETF",
    "VIXY": "VIX 단기 ETF",
    "UVXY": "VIX 1.5배 레버리지 ETF",
    "SVXY": "VIX 0.5배 인버스 ETF",
    "VIXM": "VIX 중기 ETF",
    "VXUS": "미국 외 전체주식 ETF",
    "VEA": "선진국(미국제외) ETF",
    "VWO": "신흥시장 ETF",
    "INDA": "인도 ETF",
    "EWZ": "브라질 ETF",
    "EWT": "대만 ETF",
    "EWG": "독일 ETF",
    "EWU": "영국 ETF",
    "EWC": "캐나다 ETF",
    "EWA": "호주 ETF",
    "EWQ": "프랑스 ETF",
    "EWI": "이탈리아 ETF",
    "EWP": "스페인 ETF",
    "EWL": "스위스 ETF",
    "EWD": "스웨덴 ETF",
    "EFAV": "선진국최소변동성 ETF",
    "USMV": "미국최소변동성 ETF",
    "QUAL": "미국퀄리티팩터 ETF",
    "SIZE": "미국사이즈팩터 ETF",
    "MTUM": "미국모멘텀팩터 ETF",
    "VLUE": "미국밸류팩터 ETF",
    "DGRW": "배당성장 ETF",
    "DGRO": "iShares배당성장 ETF",
    "SDY": "S&P고배당 ETF",
    "HDV": "iShares핵심고배당 ETF",
    "VYM": "뱅가드고배당수익률 ETF",
    "SCHD": "슈왑미국배당주 ETF",
    "DVY": "iShares셀렉트배당 ETF",
    "PFF": "우선주 ETF",
    "PGX": "우선주 ETF2",
    "PFFD": "글로벌X우선주 ETF",
    "HYEM": "신흥시장하이일드채권 ETF",
    "EMB": "신흥시장채권 ETF",
    "BNDX": "국제채권 ETF",
    "BWX": "국제국채 ETF",
    "WIP": "물가연동채권 ETF",
    "TIPS": "미국물가연동채권 ETF",
    "VTIP": "뱅가드단기물가연동채권 ETF",
    "STIP": "iShares단기물가연동채권 ETF",
    "IEF": "미국 7-10년국채 ETF",
    "IEI": "미국 3-7년국채 ETF",
    "SHV": "미국초단기국채 ETF",
    "BIL": "미국 1-3개월국채 ETF",
    "SGOV": "iShares0-3개월국채 ETF",
    "AGG": "미국채권 ETF",
    "BND": "뱅가드채권시장 ETF",
    "VCIT": "뱅가드중기회사채 ETF",
    "VCSH": "뱅가드단기회사채 ETF",
    "BNDW": "뱅가드글로벌채권 ETF",
    "MBB": "모기지채권 ETF",
    "VMBS": "뱅가드모기지채권 ETF",
    "MORT": "모기지REIT ETF",
    "REM": "iShares모기지REIT ETF",
    "GNMA": "모기지국채 ETF",
    "FLOT": "변동금리채권 ETF",
    "FLRN": "SPDR변동금리채권 ETF",
    "NEAR": "단기채권 ETF",
    "ICSH": "초단기채권 ETF",
    "MINT": "PIMCO단기액티브채권 ETF",
    "VRIG": "변동금리투자등급 ETF",
    "CLTL": "초단기국채 ETF",
    "GBIL": "골드만삭스단기국채 ETF",
    "TFLO": "iShares국채변동금리 ETF",
    # ── 게임/엔터/미디어 추가 ──
    "ATVI": "액티비전블리자드",
    "EA": "일렉트로닉아츠",
    "TTWO": "테이크투인터랙티브",
    "ZNGA": "징가",
    "DKNG": "드래프트킹스",
    "PENN": "PENN엔터테인먼트",
    "MGM": "MGM리조트",
    "WYNN": "윈리조트",
    "LVS": "라스베이거스샌즈",
    "CZR": "시저스엔터테인먼트",
    "MLCO": "멜코리조트앤엔터테인먼트",
    "GENI": "지니어스스포츠",
    "ALTM": "알타미디어",
    "GAMB": "갬블리",
    "GMBL": "에스포츠엔터테인먼트",
    "SKLZ": "스킬즈",
    "GFAI": "그래핀에이아이",
    "SE": "씨리밋드(쇼피/가레나)",
    "CODA": "코다옥토퍼스",
    "WMG": "워너뮤직그룹",
    "UMG": "유니버설뮤직그룹",
    "IHRT": "iHeartMedia",
    "AMCX": "AMC네트웍스",
    "VIAC": "비아컴CBS",
    "DISC": "디스커버리",
    "LIONSGATE": "라이온스게이트",
    "LGF-A": "라이온스게이트A",
    "LGF-B": "라이온스게이트B",
    "CIK": "신시내티벨",
    "IDT": "IDT코퍼레이션",
    "GTN": "그레이텔레비전",
    "SBGI": "싱클레어브로드캐스트",
    "NXST": "넥스스타미디어그룹",
    "GSAT": "글로벌스타",
    "ViaSat": "바이어셋",
    "VSAT": "바이어셋",
    "MAXR": "맥사테크놀로지스",
    "SPIR": "스파이어글로벌",
    "BGSF": "BG스태핑",
    "KFRC": "케포스",
    "TBI": "온어쎄인먼트",
    "HCSG": "헬스케어서비시스그룹",
    "USPH": "US피지컬테라피",
    "AMED": "에이메드헬스",
    "ENSG": "앙스그룹",
    "ADUS": "아두스홈케어",
    "CCRN": "크로스컨트리헬스케어",
    "AMN": "AMN헬스케어",
    "NRDY": "너디",
    "PRDO": "페르도코",
    "LAUR": "로렐에이트에듀케이션",
    "STRA": "스트레이어에듀케이션",
    "COUR": "코세라",
    "DUOL": "듀오링고",
    "CHGG": "체그",
    "LRN": "K12",
    "TWOU": "2U",
    "EDLY": "에들리",
    "AFRI": "에어플리에이션",
    "LSPD": "라이트스피드커머스",
    "GLBE": "글로벌이",
    "CART": "인스타카트(메이플리프푸드)",
    "PCTY": "페이로시티홀딩",
    "ADP": "오토매틱데이터프로세싱",
    "PAYX": "페이첵스",
    "G": "갠슬러",
    "CSGP": "코스타그룹",
    "REZI": "리세이",
    "NDAQ": "나스닥",
    "ICE": "인터컨티넨털익스체인지",
    "MSCI": "MSCI",
    "VRSK": "버리스크애널리틱스",
    "DNB": "던앤브래드스트리트",
    "NLSN": "닐슨홀딩스",
    "CIEN": "시에나",
    "COMM": "커머스코프",
    "INFN": "인피네라",
    "CALX": "칼릭스",
    "ADTRAN": "ADTRAN",
    "ADTN": "ADTRAN",
    "VIAV": "비아비솔루션즈",
    "IIVI": "II-VI(코히어런트)",
    "COHR": "코히어런트",
    "FNSR": "피니사",
    "LUMN": "루멘테크놀로지스",
    "NTGR": "넷기어",
    "CMBM": "캠브리엄네트웍스",
    "SMTC": "세마텍",
    "AIRG": "에어고",
    "ATEN": "A10네트웍스",
    "NTCT": "넷스카우트시스템즈",
    "RDWR": "래드웨어",
    "FFIV": "F5",
    "JNPR": "주니퍼네트웍스",
    "EXTR": "익스트림네트웍스",
    "HPE": "휴렛팩커드엔터프라이즈",
    "NTAP": "넷앱",
    "PSTG": "퓨어스토리지",
    "CLVT": "클래리베이트",
    "IDX": "아이덱스바이오",
    "ISCG": "iShares모멘텀 ETF",
    "VONG": "뱅가드러셀1000그로스 ETF",
    "MGK": "뱅가드메가캡그로스 ETF",
    "IVW": "iShares코어S&P500그로스 ETF",
    "SPYG": "SPDR포폴리오S&P500그로스 ETF",
    "VOOG": "뱅가드S&P500그로스 ETF",
    "IVE": "iShares코어S&P500밸류 ETF",
    "SPYV": "SPDR포폴리오S&P500밸류 ETF",
    "VOOV": "뱅가드S&P500밸류 ETF",
    "VBK": "뱅가드소형주그로스 ETF",
    "VBR": "뱅가드소형주밸류 ETF",
    "IWO": "iShares러셀2000그로스 ETF",
    "IWN": "iShares러셀2000밸류 ETF",
    "VB": "뱅가드소형주 ETF",
    "VO": "뱅가드중형주 ETF",
    "VV": "뱅가드대형주 ETF",
    "MGC": "뱅가드메가캡 ETF",
    "VXF": "뱅가드확장장세 ETF",
    "ONEQ": "피델리티나스닥컴포지트인덱스 ETF",
    "ITOT": "iShares코어미국전체주식 ETF",
    "SCHB": "슈왑미국광대주식 ETF",
    "FZILX": "피델리티인터내셔널인덱스",
    "SCHA": "슈왑미국소형주 ETF",
    "FNDF": "슈왑펀더멘탈인터내셔널라지 ETF",
    "COWZ": "파라미터스미국현금흐름킹스 ETF",
    "CAPE": "바클레이즈 ETN",
    "PKW": "인베스코바이백어치버스 ETF",
    "CSB": "VictoryShares미국500 ETF",
    "MOAT": "반에크모닝스타와이드모트 ETF",
    "GOAT": "반에크모닝스타글로벌와이드모트 ETF",
    "VIG": "뱅가드배당가치주감사 ETF",
    "NOBL": "ProShares S&P500배당귀족 ETF",
    "REGL": "ProShares S&P중형주배당귀족 ETF",
    "SMDV": "ProShares러셀2000배당귀족 ETF",
    "KNG": "FT다우존스배당&BuyBack ETF",
    "DGRS": "WisdomTree미국소형주배당 ETF",
    "DLN": "WisdomTree미국대형주배당 ETF",
    "DTD": "WisdomTree미국전체배당 ETF",
    "DES": "WisdomTree미국소형주배당 ETF",
    "EES": "WisdomTree미국소형주 ETF",
    "EFV": "iShares선진국가치팩터 ETF",
    "HEFA": "iShares통화헤지유럽 ETF",
    "HEWJ": "iShares통화헤지일본 ETF",
    "DBJP": "도이치뱅크일본통화헤지 ETF",
    "DBEF": "도이치뱅크선진국통화헤지 ETF",
    # ── 기타 잘 알려진 종목 ──
    "RIVN": "리비안",
    "F": "포드",
    "GM": "제너럴모터스",
    "STLA": "스텔란티스",
    "TM": "도요타",
    "HMC": "혼다",
    "NSANY": "닛산",
    "POAHY": "포르쉐",
    "VWAGY": "폭스바겐",
    "BMWYY": "BMW",
    "DDAIF": "다임러",
    "MBGAF": "메르세데스벤츠",
    "RACE": "페라리",
    "FCAU": "피아트크라이슬러",
    "HYMTF": "현대모터",
    "KIMTF": "기아",
    "SZKMY": "스즈키",
    "DNZOY": "덴소",
    "APTV": "앱티브",
    "VC": "비스테온",
    "THRM": "젠텍스",
    "MPAA": "모터파츠아메리카",
    "STRT": "스트라텍시큐리티",
    "AXL": "아메리칸액슬",
    "LCII": "LCI인더스트리스",
    "THO": "쏘어인더스트리스",
    "WGO": "위네베이고",
    "PII": "폴라리스",
    "HOG": "할리데이비슨",
    "YETI": "예티홀딩스",
    "FOXF": "폭스팩토리홀딩",
    "ESCA": "에스카 마린",
    "MCBC": "마스터크래프트보트홀딩",
    "HZO": "마린맥스",
    "MBUU": "마스터크래프트보트",
    "BC": "브런스윅코퍼레이션",
    "MHO": "M/I홈즈",
    "GRBK": "그린브릭파트너스",
    "JELD": "젤드웬",
    "PGTI": "PGT이노베이션스",
    "FBHS": "포춘브랜즈",
    "HOLI": "할라인테크놀로지",
    "OESX": "오리온에너지시스템즈",
    "AMSC": "아메리칸슈퍼컨덕터",
    "HPNN": "홉익스",
    "GIGA": "기가코어",
    "PERI": "페리온네트워크",
    "MGNI": "매그나이트",
    "APPS": "디지털터빈",
    "DV": "더블버파이",
    "IAS": "인테그럴애드사이언스",
    "PUBM": "퍼블매틱",
    "CRTO": "크리테오",
    "TTD": "트레이드데스크",
    "RAMP": "라이브램프홀딩스",
    "CDLX": "카딜럭스",
    "ACMR": "ACM리서치",
    "AGMH": "AGM그룹홀딩스",
    "SPNS": "사파이어원",
    "BASE": "클라리데이터베이스",
    "DBX": "드롭박스",
    "GDDY": "고대디",
    "WIX": "윅스닷컴",
    "SQSP": "스퀘어스페이스",
    "WEBL": "Direxion 데일리 다우존스인터넷 3배 ETF",
    "WEBR": "베버그릴",
    "NABL": "N-에이블",
    "CHKP": "체크포인트소프트웨어",
    "TENB": "테너블홀딩스",
    "QLYS": "퀄리스",
    "SAIL": "세일포인트테크놀로지스",
    "IRMD": "IronNet",
    "STEM": "스템",
    "ESTC": "엘라스틱",
    "SUMO": "수모로직",
    "DT": "다이나트레이스",
    "NEWR": "뉴렐릭",
    "DOMO": "도모",
    "ALTR": "알타이르",
    "GEN": "젠디지털",
    "NLOK": "노턴라이프락",
    "AVAST": "어바스트",
    "AKAM": "아카마이테크놀로지스",
    "LLNW": "라임라이트네트웍스",
    "EGIO": "에지오",
    "FSLY": "패스틀리",
    "CDW": "CDW코퍼레이션",
    "PCTY": "페이로시티",
    "SMAR": "스마트시트",
    "APPN": "앱피안",
    "CRDO": "크레도세미컨덕터",
    "SCLX": "사이클렉스테라퓨틱스",
    "AGX": "아르고그래픽스",
    "AUDC": "오디오코즈",
    "CRNC": "서런스AI",
    "CEVA": "CEVA",
    "LIQT": "LiqTech인터내셔널",
    "NNDM": "나노디멘션",
    "SSYS": "스트라타시스",
    "DDD": "3D시스템즈",
    "XONE": "ExOne",
    "MKFG": "마크포지드",
    "MTLS": "메터리알라이즈",
    "VELO": "벨로뱅크",
    "PRNT": "3D프린팅 ETF",
    "ROBO": "로보틱스&AI ETF",
    "BOTZ": "글로벌X로보틱스&AI ETF",
    "IRBO": "iShares로보틱스&AI ETF",
    "AIQ": "글로벌X인공지능&테크 ETF",
    "LRNZ": "TrueSharesAI&딥러닝 ETF",
    "MASK": "ETFMG프라이멕시코에어리얼어그리컬처 ETF",
    "PAWZ": "ProShares 펫케어 ETF",
    "PAWZ": "펫케어 ETF",
    "BUG": "글로벌X사이버시큐리티 ETF",
    "HACK": "ETFMG프라임사이버시큐리티 ETF",
    "CIBR": "퍼스트트러스트나스닥사이버시큐리티 ETF",
    "IHAK": "iShares사이버시큐리티&테크 ETF",
    "WCLD": "위스덤트리클라우드컴퓨팅 ETF",
    "CLOU": "글로벌X클라우드컴퓨팅 ETF",
    "SKYY": "퍼스트트러스트클라우드컴퓨팅 ETF",
    "IGV": "iShares소프트웨어 ETF",
    "PSJ": "인베스코다이나믹소프트웨어 ETF",
    "FINX": "글로벌X핀테크 ETF",
    "IPAY": "ETFMG프라임모바일페이먼트 ETF",
    "KOIN": "퍼스트트러스트인디아넥스트젠이코노미 ETF",
    "DIGI": "글로벌X디지털이코노미 ETF",
    "NERD": "라운드힐BITKRAFT이스포츠&디지털엔터 ETF",
    "ESPO": "반에크비디오게이밍&이스포츠 ETF",
    "HERO": "글로벌X비디오게임&이스포츠 ETF",
    "GAMR": "ETFMG비디오게임테크 ETF",
    "BETZ": "라운드힐스포츠베팅&iGaming ETF",
    "CNBS": "ARK임파일스드인베스팅 ETF",
    "POTX": "글로벌X대마초 ETF",
    "MJ": "ETFMG얼터너티브하비스트 ETF",
    "YOLO": "AdvisorShares퓨어대마초 ETF",
    "MSOS": "AdvisorShares퓨어미국대마초 ETF",
    "MJXL": "대마초2x데일리 ETF",
    "XBI": "SPDR생명공학 ETF",
    "IBB": "iShares나스닥생명공학 ETF",
    "BBH": "반에크바이오테크 ETF",
    "PBE": "인베스코다이나믹생명공학&게놈 ETF",
    "GNOM": "글로벌X게놈&바이오테크 ETF",
    "IDNA": "iShares유전체면역학&헬스케어 ETF",
    "ARKG": "ARK유전체혁명 ETF",
    "SAAS": "퍼스트트러스트SaaS ETF",
    "WCBR": "위스덤트리클라우드&사이버 ETF",
    "SNSR": "글로벌XIOT ETF",
    "NXTG": "퍼스트트러스트인디아나인터넷오브씽 ETF",
    "FIVG": "디파이언스차세대커넥티비티 ETF",
    "WUGI": "에스파르투스차세대인터넷 ETF",
    "PAVE": "글로벌X미국인프라개발 ETF",
    "IFRA": "iShares미국인프라 ETF",
    "INFU": "인프라스트럭처 ETF",
    "GBLD": "인베스코글로벌클린에너지 ETF",
    "ICLN": "iShares글로벌클린에너지 ETF",
    "QCLN": "퍼스트트러스트나스닥클린엣지그린에너지 ETF",
    "SMOG": "반에크저탄소에너지 ETF",
    "ACES": "ALPS클린에너지 ETF",
    "FSMD": "피델리티스몰-미드팩터 ETF",
    "ESGU": "iShares MSCI미국ESG셀렉트 ETF",
    "ESGV": "뱅가드ESG미국주식 ETF",
    "SUSA": "iShares MSCI미국ESG리더스 ETF",
    "DSI": "iShares MSCI KLD400소셜 ETF",
    "SUSL": "iShares ESG MSCI미국리더스 ETF",
    "NULV": "NU샤레즈ESG대형주밸류 ETF",
    "VOTE": "엔진No.1트랜스폼500 ETF",
    "EQAL": "인베스코러셀1000이퀄웨이트 ETF",
    "RSP": "인베스코S&P500이퀄웨이트 ETF",
    "EWSC": "인베스코S&P소형주이퀄웨이트 ETF",
    "RYT": "인베스코S&P500이퀄웨이트테크 ETF",
    "RYH": "인베스코S&P500이퀄웨이트헬스케어 ETF",
    "RYF": "인베스코S&P500이퀄웨이트금융 ETF",
    "RSPD": "인베스코S&P500이퀄웨이트임의소비재 ETF",
    "RSPE": "인베스코S&P500이퀄웨이트에너지 ETF",
    "RSPU": "인베스코S&P500이퀄웨이트유틸리티 ETF",
    "RSPM": "인베스코S&P500이퀄웨이트소재 ETF",
    "RSPR": "인베스코S&P500이퀄웨이트부동산 ETF",
    "RSPN": "인베스코S&P500이퀄웨이트산업재 ETF",
}


# ── 가격 조회 ──────────────────────────────────────────────

async def get_naver_price(ticker: str) -> Optional[dict]:
    """네이버 금융 API로 한국 주식 가격 조회 (캐시 90초)"""
    cached = _cache_get(ticker)
    if cached:
        return cached

    async with _get_lock(ticker):
        # lock 획득 후 재확인 (다른 코루틴이 이미 채웠을 수 있음)
        cached = _cache_get(ticker)
        if cached:
            return cached

        try:
            url = f"https://m.stock.naver.com/api/stock/{ticker}/basic"
            headers = {"User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15"}
            async with httpx.AsyncClient(timeout=10) as client:
                resp = await client.get(url, headers=headers)
                resp.raise_for_status()
                data = resp.json()

            exchange_type = data.get("stockExchangeType", {})
            exchange_code = exchange_type.get("code", "KS")
            exchange = "KOSDAQ" if exchange_code == "KQ" else "KOSPI"

            result = {
                "ticker": ticker,
                "name": data.get("stockName", ticker),
                "price": float(data.get("closePrice", "0").replace(",", "")),
                "change": float(data.get("compareToPreviousClosePrice", "0").replace(",", "")),
                "change_pct": float(data.get("fluctuationsRatio", "0")),
                "market": "KR",
                "exchange": exchange,
            }
            _cache_set(ticker, result)
            return result
        except Exception as e:
            print(f"KR 주가 조회 오류 ({ticker}): {e}")
            return None


async def get_yahoo_price(ticker: str) -> Optional[dict]:
    """Yahoo Finance API로 미국 주식 가격 조회 (캐시 90초)"""
    cache_key = f"us:{ticker}"
    cached = _cache_get(cache_key)
    if cached:
        return cached

    async with _get_lock(cache_key):
        cached = _cache_get(cache_key)
        if cached:
            return cached

        try:
            url = f"https://query1.finance.yahoo.com/v8/finance/chart/{ticker}?interval=1d&range=1d"
            headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"}
            async with httpx.AsyncClient(timeout=10) as client:
                resp = await client.get(url, headers=headers)
                resp.raise_for_status()
                data = resp.json()

            meta = data["chart"]["result"][0]["meta"]
            current_price = meta.get("regularMarketPrice", 0)
            prev_close = meta.get("chartPreviousClose") or meta.get("previousClose") or current_price
            change = current_price - prev_close
            change_pct = (change / prev_close * 100) if prev_close else 0

            exchange = meta.get("fullExchangeName", "NYSE")
            if meta.get("quoteType") == "ETF":
                exchange = "ETF"

            eng_name = meta.get("longName") or meta.get("shortName", ticker)
            name = US_NAME_KO.get(ticker.upper(), eng_name)

            # 프리/애프터 마켓 가격
            pre_price = meta.get("preMarketPrice")
            after_price = meta.get("postMarketPrice")

            result = {
                "ticker": ticker,
                "name": name,
                "price": current_price,
                "change": change,
                "change_pct": change_pct,
                "market": "US",
                "exchange": exchange,
                "pre_price": pre_price,
                "after_price": after_price,
            }
            _cache_set(cache_key, result)
            return result
        except Exception as e:
            print(f"US 주가 조회 오류 ({ticker}): {e}")
            return None


async def get_stock_price(ticker: str) -> Optional[dict]:
    """ticker로 현재가 조회 - 숫자면 KR, 아니면 US"""
    if ticker.replace("-", "").isdigit() or (len(ticker) == 6 and ticker.isdigit()):
        return await get_naver_price(ticker)
    return await get_yahoo_price(ticker)


# ── 검색 ──────────────────────────────────────────────────

async def search_naver(query: str) -> list:
    """네이버 자동완성 API로 한국 종목 검색"""
    try:
        url = f"https://ac.stock.naver.com/ac?q={query}&target=index,stock,marketindicator"
        headers = {"User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15"}
        async with httpx.AsyncClient(timeout=8) as client:
            resp = await client.get(url, headers=headers)
            data = resp.json()

        # stock 타입만 필터 (index 제외)
        items = [i for i in data.get("items", []) if i.get("typeCode") in ("KOSPI", "KOSDAQ")]
        return items[:6]
    except Exception as e:
        print(f"네이버 검색 오류: {e}")
        return []


async def search_yahoo(query: str) -> list:
    """Yahoo Finance 검색 API로 미국 종목 검색"""
    try:
        url = f"https://query1.finance.yahoo.com/v1/finance/search?q={query}&lang=en-US&region=US&quotesCount=6&newsCount=0"
        headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"}
        async with httpx.AsyncClient(timeout=8) as client:
            resp = await client.get(url, headers=headers)
            data = resp.json()

        # 미국 거래소 종목만 (한국/독일 등 제외), EQUITY/ETF만
        valid_exchanges = {"NMS", "NYQ", "NGM", "NCM", "NYSEArca", "NasdaqGS", "NasdaqGM", "NasdaqCM", "NYSE", "NASDAQ"}
        quotes = [
            q for q in data.get("quotes", [])
            if q.get("quoteType") in ("EQUITY", "ETF")
            and q.get("exchange") in valid_exchanges
        ]
        return quotes[:6]
    except Exception as e:
        print(f"Yahoo 검색 오류: {e}")
        return []


def search_ko_name(query: str) -> list[str]:
    """한글 쿼리로 US_NAME_KO 역방향 검색 → 매칭 ticker 목록 반환 (최대 6개)
    우선순위: 이름 시작 일치 > 단어 경계 일치 > 포함
    """
    q = query.strip().lower()
    if not q:
        return []

    exact_start, word_match, contains = [], [], []
    for ticker, name in US_NAME_KO.items():
        n = name.lower()
        if n.startswith(q):
            exact_start.append(ticker)
        elif any(part.startswith(q) for part in n.replace("(", " ").replace(")", " ").split()):
            word_match.append(ticker)
        elif q in n:
            contains.append(ticker)

    result = exact_start + word_match + contains
    return result[:6]


async def search_stock(query: str, market: str = "ALL") -> list:
    """종목 검색 - 네이버/Yahoo API 직접 호출 + 한글 이름 역방향 매핑"""
    import asyncio

    query = query.strip()
    if not query:
        return []

    # 한글 포함 여부 체크
    has_korean = any("가" <= c <= "힣" for c in query)

    tasks = []
    if market in ("ALL", "KR"):
        tasks.append(search_naver(query))
    # 영어이거나 ALL/US 모드면 Yahoo 검색
    if market in ("ALL", "US") and not has_korean:
        tasks.append(search_yahoo(query))

    search_results = await asyncio.gather(*tasks)

    price_tasks = []

    # KR 결과
    if market in ("ALL", "KR") and search_results:
        kr_results = search_results[0]
        for item in kr_results:
            price_tasks.append(get_naver_price(item["code"]))

    # US 결과 (영어 검색)
    if market in ("ALL", "US") and not has_korean:
        us_results = search_results[-1] if search_results else []
        for item in us_results:
            price_tasks.append(get_yahoo_price(item["symbol"]))

    # 한글 검색 → US_NAME_KO 역방향 매핑으로 미국 주식도 검색
    if has_korean and market in ("ALL", "US"):
        ko_tickers = search_ko_name(query)
        for ticker in ko_tickers:
            price_tasks.append(get_yahoo_price(ticker))

    prices = await asyncio.gather(*price_tasks)
    return [p for p in prices if p is not None]


# ── 인기 종목 ──────────────────────────────────────────────

async def get_popular_stocks(market: str = "ALL") -> list:
    """홈화면 인기 종목 - 최소 하드코딩 ticker 기반"""
    import asyncio

    tasks = []
    if market in ("ALL", "KR"):
        for ticker in POPULAR_KR:
            tasks.append(get_naver_price(ticker))
    if market in ("ALL", "US"):
        for ticker in POPULAR_US:
            tasks.append(get_yahoo_price(ticker))

    results = await asyncio.gather(*tasks)
    return [r for r in results if r is not None]
